language: node_js
node_js:
- '14.15.4'

install:
- npm install

before_script:
  - npm audit

script:
- npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: npm publish 
  on:
    repo: Displayr/ngvizApiDemonstrator
    branch: master
