version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      # look for existing cache and restore if found
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            # CircleCI will use the static fallback key v1-deps- to load the most recent valid cache
            - v1-deps- 
      # install dependencies
      - run:
          name: Install dependencies
          command: |
            npm install
            npm audit
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules   
      - run:
          name: Run build
          command: npm run build
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Publish package
                command: npm publish